@extends('layouts.app')

@section('page-title', 'Calendário')

@section('top-actions')
    <button onclick="openTaskModal()" class="inline-flex items-center gap-2 px-4 py-2 bg-zinc-900 text-white dark:bg-white dark:text-zinc-900 text-sm font-medium rounded-lg hover:bg-zinc-800 dark:hover:bg-zinc-200 transition-colors shadow-sm">
        <i class="fas fa-plus"></i> Nova Tarefa
    </button>
@endsection

@section('content')
<div class="bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-xl shadow-sm overflow-hidden flex flex-col h-[calc(100vh-140px)] min-h-[600px]">
    <div class="px-4 py-3 sm:px-6 sm:py-4 border-b border-zinc-200 dark:border-zinc-800 flex items-center justify-between bg-zinc-50/50 dark:bg-zinc-900/50">
        <div class="flex items-center gap-2 sm:gap-4">
            <button onclick="changeMonth(-1)" class="inline-flex items-center justify-center w-8 h-8 rounded-lg text-zinc-500 hover:text-zinc-900 hover:bg-zinc-200 dark:hover:text-white dark:hover:bg-zinc-800 transition-colors">
                <i class="fas fa-chevron-left text-sm"></i>
            </button>
            <span id="calendarTitle" class="text-base sm:text-lg font-semibold text-zinc-900 dark:text-white min-w-[140px] text-center capitalize"></span>
            <button onclick="changeMonth(1)" class="inline-flex items-center justify-center w-8 h-8 rounded-lg text-zinc-500 hover:text-zinc-900 hover:bg-zinc-200 dark:hover:text-white dark:hover:bg-zinc-800 transition-colors">
                <i class="fas fa-chevron-right text-sm"></i>
            </button>
        </div>
        <button onclick="goToday()" class="inline-flex items-center gap-2 px-3 py-1.5 bg-white dark:bg-zinc-800 border border-zinc-200 dark:border-zinc-700 rounded-md text-xs font-medium text-zinc-700 dark:text-zinc-300 hover:bg-zinc-50 dark:hover:bg-zinc-700 transition-colors">
            <i class="fas fa-calendar-day text-zinc-400"></i> <span class="hidden sm:inline">Hoje</span>
        </button>
    </div>

    <!-- Calendar Grid -->
    <div class="flex-1 flex flex-col overflow-hidden">
        <div class="grid grid-cols-7 border-b border-zinc-200 dark:border-zinc-800 bg-zinc-50/80 dark:bg-zinc-900/80">
            @foreach(['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'] as $day)
                <div class="py-2 text-center text-xs font-medium text-zinc-500 dark:text-zinc-400 uppercase tracking-wider border-r border-zinc-200 dark:border-zinc-800 last:border-r-0">
                    <span class="hidden md:inline">{{ $day }}</span>
                    <span class="md:hidden">{{ substr($day, 0, 1) }}</span>
                </div>
            @endforeach
        </div>
        <div id="calendarGrid" class="flex-1 grid grid-cols-7 auto-rows-fr bg-zinc-200 dark:bg-zinc-800 gap-[1px] border-b border-zinc-200 dark:border-zinc-800 overflow-y-auto">
            <!-- Grid generated by JS -->
        </div>
    </div>
</div>

{{-- Task Modal --}}
<div id="taskModal" class="fixed inset-0 z-50 items-center justify-center bg-black/50 backdrop-blur-sm hidden opacity-0 transition-opacity duration-300">
    <div class="bg-white dark:bg-zinc-900 rounded-xl shadow-xl w-full max-w-md mx-4 overflow-hidden transform scale-95 transition-transform duration-300 flex flex-col max-h-[90vh]">
        <div class="px-6 py-4 border-b border-zinc-200 dark:border-zinc-800 flex justify-between items-center bg-zinc-50/50 dark:bg-zinc-800/50">
            <h3 id="modalTitle" class="text-lg font-semibold text-zinc-900 dark:text-white">Nova Tarefa</h3>
            <button onclick="closeTaskModal()" class="text-zinc-400 hover:text-zinc-600 dark:hover:text-zinc-200 transition-colors">
                <i class="fas fa-times text-lg"></i>
            </button>
        </div>

        <form id="taskForm" class="p-6 overflow-y-auto flex-1">
            <input type="hidden" id="taskId" value="">

            <div class="mb-4">
                <label class="block text-sm font-medium text-zinc-700 dark:text-zinc-300 mb-1.5">Título <span class="text-red-500">*</span></label>
                <input type="text" id="taskTitle" required placeholder="Ex: Imprimir lote de vasos" 
                       class="w-full px-4 py-2 bg-zinc-50 dark:bg-zinc-950 border border-zinc-300 dark:border-zinc-800 rounded-lg text-sm text-zinc-900 dark:text-white focus:ring-2 focus:ring-zinc-900 dark:focus:ring-zinc-100 focus:border-transparent transition-shadow outline-none">
            </div>

            <div class="mb-4">
                <label class="block text-sm font-medium text-zinc-700 dark:text-zinc-300 mb-1.5">Descrição</label>
                <textarea id="taskDesc" rows="3" placeholder="Detalhes da tarefa..." 
                          class="w-full px-4 py-2 bg-zinc-50 dark:bg-zinc-950 border border-zinc-300 dark:border-zinc-800 rounded-lg text-sm text-zinc-900 dark:text-white focus:ring-2 focus:ring-zinc-900 dark:focus:ring-zinc-100 focus:border-transparent transition-shadow outline-none resize-none"></textarea>
            </div>

            <div class="grid grid-cols-2 gap-4 mb-4">
                <div>
                    <label class="block text-sm font-medium text-zinc-700 dark:text-zinc-300 mb-1.5">Data <span class="text-red-500">*</span></label>
                    <input type="date" id="taskDate" required 
                           class="w-full px-4 py-2 bg-zinc-50 dark:bg-zinc-950 border border-zinc-300 dark:border-zinc-800 rounded-lg text-sm text-zinc-900 dark:text-white focus:ring-2 focus:ring-zinc-900 dark:focus:ring-zinc-100 focus:border-transparent transition-shadow outline-none">
                </div>
                <div>
                    <label class="block text-sm font-medium text-zinc-700 dark:text-zinc-300 mb-1.5">Prioridade</label>
                    <select id="taskPriority" 
                            class="w-full px-4 py-2 bg-zinc-50 dark:bg-zinc-950 border border-zinc-300 dark:border-zinc-800 rounded-lg text-sm text-zinc-900 dark:text-white focus:ring-2 focus:ring-zinc-900 dark:focus:ring-zinc-100 focus:border-transparent transition-shadow outline-none appearance-none pr-8 bg-[url('data:image/svg+xml;charset=US-ASCII,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%22292.4%22%20height%3D%22292.4%22%3E%3Cpath%20fill%3D%22%239ca3af%22%20d%3D%22M287%2069.4a17.6%2017.6%200%200%200-13-5.4H18.4c-5%200-9.3%201.8-12.9%205.4A17.6%2017.6%200%200%200%200%2082.2c0%205%201.8%209.3%205.4%2012.9l128%20127.9c3.6%203.6%207.8%205.4%2012.8%205.4s9.2-1.8%2012.8-5.4L287%2095c3.5-3.5%205.4-7.8%205.4-12.8%200-5-1.9-9.2-5.5-12.8z%22%2F%3E%3C%2Fsvg%3E')] bg-[length:12px_12px] bg-[right_12px_center] bg-no-repeat">
                        <option value="low">🟡 Baixa</option>
                        <option value="medium" selected>🟠 Média</option>
                        <option value="high">🔴 Alta</option>
                    </select>
                </div>
            </div>

            <div class="grid grid-cols-2 gap-4 mb-6">
                <div>
                    <label class="block text-sm font-medium text-zinc-700 dark:text-zinc-300 mb-1.5">Status</label>
                    <select id="taskStatus" 
                            class="w-full px-4 py-2 bg-zinc-50 dark:bg-zinc-950 border border-zinc-300 dark:border-zinc-800 rounded-lg text-sm text-zinc-900 dark:text-white focus:ring-2 focus:ring-zinc-900 dark:focus:ring-zinc-100 focus:border-transparent transition-shadow outline-none appearance-none pr-8 bg-[url('data:image/svg+xml;charset=US-ASCII,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%22292.4%22%20height%3D%22292.4%22%3E%3Cpath%20fill%3D%22%239ca3af%22%20d%3D%22M287%2069.4a17.6%2017.6%200%200%200-13-5.4H18.4c-5%200-9.3%201.8-12.9%205.4A17.6%2017.6%200%200%200%200%2082.2c0%205%201.8%209.3%205.4%2012.9l128%20127.9c3.6%203.6%207.8%205.4%2012.8%205.4s9.2-1.8%2012.8-5.4L287%2095c3.5-3.5%205.4-7.8%205.4-12.8%200-5-1.9-9.2-5.5-12.8z%22%2F%3E%3C%2Fsvg%3E')] bg-[length:12px_12px] bg-[right_12px_center] bg-no-repeat">
                        <option value="pending">Pendente</option>
                        <option value="in_progress">Em Andamento</option>
                        <option value="completed">Concluída</option>
                    </select>
                </div>
                <div>
                    <label class="block text-sm font-medium text-zinc-700 dark:text-zinc-300 mb-1.5">Cor</label>
                    <div class="flex items-center gap-2">
                        <input type="color" id="taskColor" value="#6366f1" 
                               class="w-10 h-10 p-0.5 bg-zinc-50 dark:bg-zinc-950 border border-zinc-300 dark:border-zinc-800 rounded-lg cursor-pointer">
                        <span class="text-xs text-zinc-500 dark:text-zinc-400">Marcador</span>
                    </div>
                </div>
            </div>

            <div class="flex items-center justify-between pt-4 border-t border-zinc-100 dark:border-zinc-800 mt-auto">
                <button type="button" id="deleteTaskBtn" onclick="deleteTask()" style="display: none;" 
                        class="px-4 py-2 text-red-600 dark:text-red-400 text-sm font-medium hover:bg-red-50 dark:hover:bg-red-500/10 rounded-lg transition-colors">
                    <i class="fas fa-trash-alt mr-1"></i> Excluir
                </button>
                <div class="flex items-center gap-2 ml-auto">
                    <button type="button" onclick="closeTaskModal()" class="px-4 py-2 text-zinc-600 dark:text-zinc-400 hover:text-zinc-900 dark:hover:text-white text-sm font-medium transition-colors">
                        Cancelar
                    </button>
                    <button type="submit" class="inline-flex items-center gap-2 px-4 py-2 bg-zinc-900 text-white dark:bg-white dark:text-zinc-900 text-sm font-medium rounded-lg hover:bg-zinc-800 dark:hover:bg-zinc-200 transition-colors">
                        <i class="fas fa-check"></i> Salvar
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

@section('scripts')
<script>
const MONTHS_PT = ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'];
const DAYS_PT = ['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'];
const csrfToken = document.querySelector('meta[name="csrf-token"]').content;

let currentYear, currentMonth;
let tasks = [];

function init() {
    const now = new Date();
    currentYear = now.getFullYear();
    currentMonth = now.getMonth();
    renderCalendar();
}

function changeMonth(delta) {
    currentMonth += delta;
    if (currentMonth > 11) { currentMonth = 0; currentYear++; }
    if (currentMonth < 0) { currentMonth = 11; currentYear--; }
    renderCalendar();
}

function goToday() {
    const now = new Date();
    currentYear = now.getFullYear();
    currentMonth = now.getMonth();
    renderCalendar();
}

async function renderCalendar() {
    document.getElementById('calendarTitle').textContent = `${MONTHS_PT[currentMonth]} ${currentYear}`;

    // Fetch tasks
    try {
        const res = await fetch(`{{ url('calendar/tasks') }}?month=${currentMonth + 1}&year=${currentYear}`);
        if(res.ok) tasks = await res.json();
    } catch(e) {
        console.error("Failed to load tasks", e);
    }

    const grid = document.getElementById('calendarGrid');
    grid.innerHTML = '';

    const firstDay = new Date(currentYear, currentMonth, 1).getDay();
    const daysInMonth = new Date(currentYear, currentMonth + 1, 0).getDate();
    const daysInPrev = new Date(currentYear, currentMonth, 0).getDate();
    const today = new Date();

    // Previous month padding
    for (let i = firstDay - 1; i >= 0; i--) {
        const el = createDayCell(daysInPrev - i, true);
        grid.appendChild(el);
    }

    // Current month
    for (let d = 1; d <= daysInMonth; d++) {
        const isToday = today.getFullYear() === currentYear && today.getMonth() === currentMonth && today.getDate() === d;
        const el = createDayCell(d, false, isToday);
        grid.appendChild(el);
    }

    // Next month padding
    const totalCells = grid.children.length;
    const remaining = (Math.ceil(totalCells / 7) * 7) - totalCells;
    for (let i = 1; i <= remaining; i++) {
        const el = createDayCell(i, true);
        grid.appendChild(el);
    }
}

function createDayCell(day, otherMonth, isToday = false) {
    const cell = document.createElement('div');
    
    // Base classes
    cell.className = 'flex flex-col p-1 sm:p-2 min-h-[80px] sm:min-h-[100px] transition-colors overflow-hidden group hover:z-10 relative cursor-pointer ' 
                   + (otherMonth ? 'bg-zinc-50/50 dark:bg-zinc-900/50 text-zinc-400 dark:text-zinc-600' : 'bg-white dark:bg-zinc-900 hover:bg-zinc-50 dark:hover:bg-zinc-800/80')
                   + (isToday ? ' bg-indigo-50/30 dark:bg-indigo-900/20' : '');

    const header = document.createElement('div');
    header.className = 'flex items-start justify-between mb-1';

    const num = document.createElement('div');
    num.className = 'flex items-center justify-center w-6 h-6 sm:w-7 sm:h-7 rounded-full text-xs font-semibold '
                  + (isToday ? 'bg-indigo-600 text-white' : (otherMonth ? 'text-zinc-400 dark:text-zinc-600' : 'text-zinc-700 dark:text-zinc-300 group-hover:bg-zinc-100 dark:group-hover:bg-zinc-800 transition-colors'));
    num.textContent = day;
    header.appendChild(num);

    const addBtn = document.createElement('div');
    addBtn.className = 'opacity-0 group-hover:opacity-100 transition-opacity text-zinc-400 hover:text-zinc-600 dark:hover:text-zinc-200 text-xs p-1 rounded hover:bg-zinc-200 dark:hover:bg-zinc-700';
    addBtn.innerHTML = '<i class="fas fa-plus"></i>';
    if(!otherMonth) header.appendChild(addBtn);

    cell.appendChild(header);

    if (!otherMonth) {
        // Add tasks for this day
        const dateStr = `${currentYear}-${String(currentMonth + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
        // Ensure due_date is treated correctly (taking first 10 chars handles YYYY-MM-DD format safely)
        const dayTasks = tasks.filter(t => t.due_date && t.due_date.substring(0, 10) === dateStr);

        const tasksDiv = document.createElement('div');
        tasksDiv.className = 'flex flex-col gap-1 overflow-y-auto w-full no-scrollbar flex-1';

        dayTasks.forEach(task => {
            const t = document.createElement('div');
            
            // Determine Tailwind border color class mapping or just use inline style for border
            
            t.className = `text-[10px] sm:text-xs font-medium px-1.5 sm:px-2 py-1 rounded border-l-2 truncate transition-opacity hover:opacity-80 dark:bg-zinc-800 bg-zinc-100 `
                        + (task.status === 'completed' ? 'line-through opacity-50 text-zinc-500 dark:text-zinc-400' : 'text-zinc-700 dark:text-zinc-200');
            t.style.borderLeftColor = task.color || '#6366f1';
            
            // Add priority indicator if needed
            let icon = '';
            if(task.priority === 'high') icon = '<i class="fas fa-exclamation-circle text-red-500 mr-1"></i>';
            if(task.status === 'completed') icon = '<i class="fas fa-check-circle text-emerald-500 mr-1"></i>';
            
            t.innerHTML = icon + task.title;
            
            t.addEventListener('click', (e) => {
                e.stopPropagation();
                openTaskModal(task);
            });
            tasksDiv.appendChild(t);
        });

        cell.appendChild(tasksDiv);

        // Click to create new task
        cell.addEventListener('click', () => {
             openTaskModal(null, dateStr);
        });
    }

    return cell;
}

const taskModal = document.getElementById('taskModal');
const modalInner = taskModal.querySelector('.bg-white');

function openTaskModal(task = null, date = null) {
    const deleteBtn = document.getElementById('deleteTaskBtn');

    if (task) {
        document.getElementById('modalTitle').textContent = 'Editar Tarefa';
        document.getElementById('taskId').value = task.id;
        document.getElementById('taskTitle').value = task.title;
        document.getElementById('taskDesc').value = task.description || '';
        document.getElementById('taskDate').value = task.due_date ? task.due_date.substring(0, 10) : '';
        document.getElementById('taskPriority').value = task.priority || 'medium';
        document.getElementById('taskStatus').value = task.status || 'pending';
        document.getElementById('taskColor').value = task.color || '#6366f1';
        deleteBtn.style.display = 'inline-flex';
    } else {
        document.getElementById('modalTitle').textContent = 'Nova Tarefa';
        document.getElementById('taskId').value = '';
        document.getElementById('taskTitle').value = '';
        document.getElementById('taskDesc').value = '';
        
        let targetDate = date;
        if(!targetDate) {
            const tzoffset = (new Date()).getTimezoneOffset() * 60000;
            targetDate = (new Date(Date.now() - tzoffset)).toISOString().split('T')[0];
        }
        
        document.getElementById('taskDate').value = targetDate;
        document.getElementById('taskPriority').value = 'medium';
        document.getElementById('taskStatus').value = 'pending';
        document.getElementById('taskColor').value = '#6366f1';
        deleteBtn.style.display = 'none';
    }

    taskModal.classList.remove('hidden');
    // Small delay to allow display:block to apply before animating opacity
    setTimeout(() => {
        taskModal.classList.remove('opacity-0');
        modalInner.classList.remove('scale-95');
        modalInner.classList.add('scale-100');
    }, 10);
}

function closeTaskModal() {
    taskModal.classList.add('opacity-0');
    modalInner.classList.remove('scale-100');
    modalInner.classList.add('scale-95');
    
    setTimeout(() => {
        taskModal.classList.add('hidden');
    }, 300);
}

document.getElementById('taskForm').addEventListener('submit', async (e) => {
    e.preventDefault();

    const id = document.getElementById('taskId').value;
    const data = {
        title: document.getElementById('taskTitle').value,
        description: document.getElementById('taskDesc').value,
        due_date: document.getElementById('taskDate').value,
        priority: document.getElementById('taskPriority').value,
        status: document.getElementById('taskStatus').value,
        color: document.getElementById('taskColor').value,
    };

    const url = id ? `{{ url('calendar/tasks') }}/${id}` : '{{ route("calendar.tasks.store") }}';
    const method = id ? 'PUT' : 'POST';

    try {
        await fetch(url, {
            method,
            headers: {
                'Content-Type': 'application/json',
                'X-CSRF-TOKEN': csrfToken,
            },
            body: JSON.stringify(data),
        });
        
        closeTaskModal();
        renderCalendar();
    } catch(e) {
        alert('Erro ao salvar a tarefa');
        console.error(e);
    }
});

async function deleteTask() {
    const id = document.getElementById('taskId').value;
    if (!id || !confirm('Excluir esta tarefa?')) return;

    try {
        await fetch(`{{ url('calendar/tasks') }}/${id}`, {
            method: 'DELETE',
            headers: { 'X-CSRF-TOKEN': csrfToken },
        });

        closeTaskModal();
        renderCalendar();
    } catch(e) {
        alert('Erro ao excluir tarefa');
        console.error(e);
    }
}

// Close modal on click outside
taskModal.addEventListener('click', (e) => {
    if (e.target === taskModal) {
        closeTaskModal();
    }
});

init();
</script>

<style>
/* Hide scrollbar for task list but allow scrolling */
.no-scrollbar::-webkit-scrollbar {
    display: none;
}
.no-scrollbar {
    -ms-overflow-style: none;
    scrollbar-width: none;
}
</style>
@endsection
